import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "app.html");
const outputPath = path.join(root, "login.htm");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function dataUri(relativePath, mimeType) {
  const data = fs.readFileSync(path.join(root, relativePath)).toString("base64");
  return `data:${mimeType};base64,${data}`;
}

function htmlAscii(value) {
  return [...value].map((character) => {
    const codePoint = character.codePointAt(0);
    return codePoint <= 0x7f ? character : `&#${codePoint};`;
  }).join("");
}

function cssAscii(value) {
  return [...value].map((character) => {
    const codePoint = character.codePointAt(0);
    return codePoint <= 0x7f ? character : `\\${codePoint.toString(16)} `;
  }).join("");
}

function jsAscii(value) {
  return [...value].map((character) => {
    const codePoint = character.codePointAt(0);
    if (codePoint <= 0x7f) return character;
    if (codePoint <= 0xffff) return `\\u${codePoint.toString(16).padStart(4, "0")}`;

    const offset = codePoint - 0x10000;
    const high = 0xd800 + (offset >> 10);
    const low = 0xdc00 + (offset & 0x3ff);
    return `\\u${high.toString(16)}\\u${low.toString(16)}`;
  }).join("");
}

const embeddedImages = new Map([
  ["assets/images/favicon.svg", dataUri("assets/images/favicon.svg", "image/svg+xml")],
  ["assets/images/login-surveillance.svg", dataUri("assets/images/login-surveillance.svg", "image/svg+xml")],
  ["assets/images/mock-front-door.svg", dataUri("assets/images/mock-front-door.svg", "image/svg+xml")],
  ["assets/images/mock-driveway.svg", dataUri("assets/images/mock-driveway.svg", "image/svg+xml")],
  ["assets/images/mock-backyard.svg", dataUri("assets/images/mock-backyard.svg", "image/svg+xml")],
  ["assets/images/mock-garage.svg", dataUri("assets/images/mock-garage.svg", "image/svg+xml")],
  ["assets/images/mock-living-room.svg", dataUri("assets/images/mock-living-room.svg", "image/svg+xml")],
  ["assets/images/mock-side-gate.svg", dataUri("assets/images/mock-side-gate.svg", "image/svg+xml")]
]);

function inlineCss(relativePath) {
  let css = read(relativePath);
  css = css.replace(
    /url\((["']?)\.\.\/images\/login-surveillance\.svg\1\)/g,
    `url("${embeddedImages.get("assets/images/login-surveillance.svg")}")`
  );
  return `<style data-source="${relativePath}">\n${cssAscii(css)}\n</style>`;
}

function inlineScript(relativePath) {
  let source = read(relativePath);
  for (const [imagePath, uri] of embeddedImages) {
    source = source.replaceAll(imagePath, uri);
  }
  source = jsAscii(source).replace(/<\/script/gi, "<\\/script");
  return `<script data-source="${relativePath}">\n${source}\n</script>`;
}

let html = htmlAscii(read("app.html"));

html = html
  .replace(
    '<!-- Source shell. Run `node scripts/build-login.mjs` to generate Blue Iris\'s self-contained login.htm entry. -->',
    "<!-- Generated by scripts/build-login.mjs. Edit app.html or assets, then rebuild. -->"
  )
  .replace(
    '<link rel="icon" href="assets/images/favicon.svg" type="image/svg+xml">',
    () => `<link rel="icon" href="${embeddedImages.get("assets/images/favicon.svg")}" type="image/svg+xml">`
  )
  .replace(/\s*<link rel="manifest" href="manifest\.webmanifest">/, "")
  .replace(
    '<link rel="stylesheet" href="assets/vendor/bootstrap.min.css">',
    () => inlineCss("assets/vendor/bootstrap.min.css")
  )
  .replace(
    '<link rel="stylesheet" href="assets/css/app.css">',
    () => inlineCss("assets/css/app.css")
  );

for (const sourcePath of [
  "assets/vendor/bootstrap.bundle.min.js",
  "assets/vendor/clappr.min.js",
  "assets/js/md5.js",
  "assets/js/mock-data.js",
  "assets/js/api.js",
  "assets/js/audio-player.js",
  "assets/js/app.js"
]) {
  html = html.replace(
    `<script src="${sourcePath}"></script>`,
    () => inlineScript(sourcePath)
  );
}

const externalTags = [...html.matchAll(/<(?:script|link)\b[^>]*>/gi)]
  .map((match) => match[0])
  .filter((tag) => /\s(?:src|href)=["'](?!data:|#)/i.test(tag));
const externalAssets = externalTags
  .map((tag) => tag.match(/\s(?:src|href)=["'](?!data:|#)([^"']+)/i)?.[1])
  .filter(Boolean);

if (externalAssets.length) {
  throw new Error(`Generated login.htm still has external assets: ${externalTags.join(", ")}`);
}
if (/[^\x00-\x7f]/.test(html)) {
  throw new Error("Generated login.htm contains non-ASCII characters that Blue Iris may mis-encode.");
}

fs.writeFileSync(outputPath, html);
console.log(`Generated ${path.relative(root, outputPath)} (${Buffer.byteLength(html).toLocaleString()} bytes).`);
